=== ANamelessWolf/urabe/testing/json/Tester/KanojoX-tester-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "#/KanojoX-tester-schema.json",
    "type": "object",
    "title": "KanojoX Test data",
    "description": "Defines the data used to test the KanojoX Class",
    "properties": {
        "connection": {
            "$id": "#/properties/connection",
            "type": "object",
            "title": "The connection data",
            "description": "Define the necessary connection elements to build a connection string",
            "$ref": "../schema/connection-template.json"
        },
        "driver": {
            "$id": "#/properties/driver",
            "type": "string",
            "title": "Connection Driver",
            "description": "The name of the connection driver supported by urabe",
            "examples": [
                "MYSQL",
                "PG",
                "ORACLE"
            ]
        },
        "sql_no_params": {
            "$id": "#/properties/sql_no_params",
            "type": "string",
            "title": "Normal select test",
            "description": "Defines a query with no binding parameters used to test a Selection Query"
        },
        "sql_params": {
            "$id": "#/properties/sql_params",
            "type": "string",
            "title": "Normal select test",
            "description": "Defines a query with binding parameters used to test a Selection Query"
        },
        "update_sql_params": {
            "$id": "#/properties/update_sql_params",
            "type": "string",
            "title": "Execute query test",
            "description": "Defines an update query with no binding parameters used to test the execute query functionality"
        },
        "update_sql_no_params": {
            "$id": "#/properties/update_sql_no_params",
            "type": "string",
            "title": "Execute query test",
            "description": "Defines an update query with binding parameters used to test the execute query functionality"
        },
        "table_name": {
            "$id": "#/properties/table_name",
            "type": "string",
            "title": "The table name",
            "description": "Used to test the selection of a table definition"
        },
        "schema": {
            "$id": "#/properties/schema",
            "type": "string",
            "title": "The database schema",
            "description": "When PG driver is given, some queries might need the schema property"
        },
        "owner": {
            "$id": "#/properties/owner",
            "type": "string",
            "title": "The database owner",
            "description": "When ORACLE driver is given, some queries might need the owner property"
        }
    },
    "required": [
        "connection",
        "driver",
        "sql_no_params",
        "sql_params",
        "update_sql_params",
        "update_sql_no_params",
        "table_name"
    ]
}

=== ANamelessWolf/urabe/testing/json/Tester/KanojoX-tester-example.json
{
    "connection": {
        "host": "127.0.0.1",
        "user_name": "user",
        "password": "*********",
        "port": 3306,
        "db_name": "my_database"
    },
    "driver": "MYSQL",
    "sql_no_params": "SELECT * FROM table_name LIMIT 5",
    "sql_params": "SELECT * FROM table_name LIMIT $1",
    "update_sql_params": "UPDATE table_name SET column = $1 WHERE gid = $2",
    "update_sql_no_params": "UPDATE table_name SET column = 'new_value'",
    "table_name": "table_name",
    "schema": "public",
    "owner": "public"
}
